from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
from numpy.typing import NDArray

from ..hilbert import DetSector


def _count(words: NDArray[Any]) -> NDArray[np.int64]:
    """Count occupied spin orbitals in packed words."""
    return np.bitwise_count(words).sum(axis=-1, dtype=np.int64)


def occupation(ket: Any, spin: int, p: int) -> NDArray[np.float64]:
    """Return n_{spin,p}(ket)."""
    ket = np.asarray(ket, dtype=np.uint64)
    spin = int(spin)
    p = int(p)
    word = p >> 6
    bit = np.uint64(1) << np.uint64(p & 63)
    return ((ket[:, spin, word] & bit) != 0).astype(np.float64)


def _parity(ket: NDArray[np.uint64], spin: int, p: int) -> NDArray[np.int64]:
    """Return the Jordan-Wigner count before spin orbital (spin, p)."""
    word = p >> 6
    before = np.zeros(ket.shape[0], dtype=np.int64)
    if spin == 1:
        before += _count(ket[:, 0, :])
    if word:
        before += _count(ket[:, spin, :word])
    mask = (
        (np.uint64(1) << np.uint64(p & 63)) - np.uint64(1)
        if p & 63
        else np.uint64(0)
    )
    if mask:
        before += np.bitwise_count(ket[:, spin, word] & mask).astype(np.int64)
    return before


def annihilate(
    ket: Any,
    spin: int,
    p: int,
) -> tuple[NDArray[np.uint64], NDArray[np.float64], NDArray[np.bool_]]:
    """Apply c_{spin,p} to each ket."""
    ket = np.ascontiguousarray(ket, dtype=np.uint64)
    spin = int(spin)
    p = int(p)
    word = p >> 6
    bit = np.uint64(1) << np.uint64(p & 63)

    active = (ket[:, spin, word] & bit) != 0
    bra = np.ascontiguousarray(ket.copy())
    bra[active, spin, word] &= ~bit
    sign = np.where(_parity(ket, spin, p) & 1, -1.0, 1.0)
    return bra, sign.astype(np.float64), active


def create(
    ket: Any,
    spin: int,
    p: int,
) -> tuple[NDArray[np.uint64], NDArray[np.float64], NDArray[np.bool_]]:
    """Apply c^dagger_{spin,p} to each ket."""
    ket = np.ascontiguousarray(ket, dtype=np.uint64)
    spin = int(spin)
    p = int(p)
    word = p >> 6
    bit = np.uint64(1) << np.uint64(p & 63)

    active = (ket[:, spin, word] & bit) == 0
    bra = np.ascontiguousarray(ket.copy())
    bra[active, spin, word] |= bit
    sign = np.where(_parity(ket, spin, p) & 1, -1.0, 1.0)
    return bra, sign.astype(np.float64), active


def number(
    ket: Any,
    spin: int | None = None,
    p: int | None = None,
) -> NDArray[np.float64]:
    """Return particle number on an orbital, spin block, or full ket."""
    ket = np.asarray(ket, dtype=np.uint64)
    if p is not None:
        if spin is None:
            return occupation(ket, 0, int(p)) + occupation(ket, 1, int(p))
        return occupation(ket, int(spin), int(p))
    if spin is not None:
        return _count(ket[:, int(spin), :]).astype(np.float64)
    return (
        _count(ket[:, 0, :]).astype(np.float64)
        + _count(ket[:, 1, :]).astype(np.float64)
    )


def sz(ket: Any) -> NDArray[np.float64]:
    """Return S_z(ket) = (N_alpha - N_beta) / 2."""
    ket = np.asarray(ket, dtype=np.uint64)
    return 0.5 * (
        _count(ket[:, 0, :]).astype(np.float64)
        - _count(ket[:, 1, :]).astype(np.float64)
    )


@dataclass(frozen=True, slots=True)
class Number:
    """Particle-number operator."""

    sector: Any

    def diag(self, ket: Any) -> NDArray[np.float64]:
        return number(ket)

    def local_conn(
        self,
        ket: Any,
    ) -> tuple[
        NDArray[np.float64],
        NDArray[np.int64],
        NDArray[np.uint64],
        NDArray[np.float64],
    ]:
        ket = np.ascontiguousarray(ket, dtype=np.uint64)
        return (
            self.diag(ket),
            np.zeros(ket.shape[0] + 1, dtype=np.int64),
            ket[:0].copy(),
            np.empty(0, dtype=np.float64),
        )


@dataclass(frozen=True, slots=True)
class Sz:
    """Spin-z operator."""

    sector: Any

    def diag(self, ket: Any) -> NDArray[np.float64]:
        return sz(ket)

    def local_conn(
        self,
        ket: Any,
    ) -> tuple[
        NDArray[np.float64],
        NDArray[np.int64],
        NDArray[np.uint64],
        NDArray[np.float64],
    ]:
        ket = np.ascontiguousarray(ket, dtype=np.uint64)
        return (
            self.diag(ket),
            np.zeros(ket.shape[0] + 1, dtype=np.int64),
            ket[:0].copy(),
            np.empty(0, dtype=np.float64),
        )


@dataclass(frozen=True, slots=True)
class S2:
    """Total spin-squared operator.

    ``local_conn`` returns the diagonal S_z^2 + (N_single / 2) term plus
    spin-exchange bras generated by S_- S_+ and S_+ S_-.
    """

    sector: Any

    def diag(self, ket: Any) -> NDArray[np.float64]:
        ket = np.asarray(ket, dtype=np.uint64)

        if isinstance(self.sector, DetSector):
            n_alpha = _count(ket[:, 0])
            n_beta = _count(ket[:, 1])
            n_double = _count(ket[:, 0] & ket[:, 1])
            n_single = n_alpha + n_beta - 2 * n_double
            m = 0.5 * (n_alpha - n_beta)
            return m * m + 0.5 * n_single.astype(np.float64)

        raise TypeError(f"unsupported sector: {type(self.sector).__name__}")

    def local_conn(
        self,
        ket: Any,
    ) -> tuple[
        NDArray[np.float64],
        NDArray[np.int64],
        NDArray[np.uint64],
        NDArray[np.float64],
    ]:
        """Return diagonal, CSR pointer, spin-exchange bras, and values."""
        ket = np.ascontiguousarray(ket, dtype=np.uint64)
        diag = self.diag(ket)
        n_ket = int(ket.shape[0])

        if not isinstance(self.sector, DetSector):
            raise TypeError(f"unsupported sector: {type(self.sector).__name__}")

        norb = int(self.sector.norb)
        orb = np.arange(norb, dtype=np.int64)
        word = orb >> 6
        bit = np.left_shift(np.uint64(1), (orb & 63).astype(np.uint64))

        alpha = (ket[:, 0, word] & bit) != 0
        beta = (ket[:, 1, word] & bit) != 0
        aonly = alpha & ~beta
        bonly = beta & ~alpha
        single = alpha ^ beta

        count = aonly.sum(axis=1, dtype=np.int64) * bonly.sum(axis=1, dtype=np.int64)
        ptr = np.empty(n_ket + 1, dtype=np.int64)
        ptr[0] = 0
        np.cumsum(count, out=ptr[1:])

        bra = np.empty((int(ptr[-1]),) + ket.shape[1:], dtype=np.uint64)
        val = np.empty(int(ptr[-1]), dtype=np.float64)

        # Prefix parity over singly occupied orbitals gives the exchange sign.
        prefix = np.empty((n_ket, norb + 1), dtype=np.int64)
        prefix[:, 0] = 0
        np.cumsum(single, axis=1, dtype=np.int64, out=prefix[:, 1:])

        for iket in range(n_ket):
            lo = int(ptr[iket])
            hi = int(ptr[iket + 1])
            if lo == hi:
                continue

            pa = np.flatnonzero(aonly[iket])
            qb = np.flatnonzero(bonly[iket])
            p = np.repeat(pa, qb.size)
            q = np.tile(qb, pa.size)
            item = np.arange(p.size)

            y = np.repeat(ket[iket : iket + 1], p.size, axis=0)
            wp, bp = word[p], bit[p]
            wq, bq = word[q], bit[q]

            y[item, 0, wp] &= ~bp
            y[item, 1, wp] |= bp
            y[item, 1, wq] &= ~bq
            y[item, 0, wq] |= bq

            left = np.minimum(p, q)
            right = np.maximum(p, q)
            parity = (prefix[iket, right] - prefix[iket, left + 1]) & 1

            bra[lo:hi] = y
            val[lo:hi] = 2.0 * parity.astype(np.float64) - 1.0

        return diag, ptr, bra, val
